### ISSUE TITLE
Product GET api

### ISSUE THREAD

**Issue by Jeanosis** [Jeanosis/product_aggregator#5]
A GET api for a product should be added.  
Path: `/api/product/:product_id`.
Query parameters:
1. `start_date` - date, format YYYY-MM-DD(2017-10-07).
1. `end_date` - date, same as start_date.

Response:
```JSON
{
    "name": "product_name",
    "price": {
        "current": 0,
        "daily": [
            {
                "value": 0,
                "date": "2017-10-07"
            }
        ]
    }
}
```

**Comment by Jeanosis** [comment]
Use `.json` instead of `.send`.

**Comment by slava-yefremov** [comment]
Done
